catalog:
  '@commitlint/cli': ^20.4.1
  '@commitlint/config-conventional': ^20.4.1
  '@types/node': ^25.2.3
  '@vitest/coverage-v8': ^4.0.18
  eslint: ^9.39.2
  husky: ^9.1.7
  multiformats: ^13.4.2
  typescript: ^5.9.3
  typescript-eslint: ^8.56.0
  vitest: ^4.0.18
  zod: ^4.3.6
